Text_PictureBookShelf:
	.string "There's a set of POKéMON picture books.$"

Text_BookShelf:
	.string "Wow!\n"
	.string "Unmengen Bücher über POKéMON.$"

Text_PokemonCenterBookShelf:
	.string "POKéMON-Magazine!\n"
	.string "DER POKéMON FREUND…\p"
	.string "POKéMON HANDBUCH…\n"
	.string "GELIEBTE POKéMON…$"

Text_Vase:
	.string "This vase looks expensive…\n"
	.string "Peered inside…\p"
	.string "But, it was empty.$"

Text_EmptyTrashCan:
	.string "It's empty.$"

Text_ShopShelf:
	.string "Die Regale biegen sich unter dem\n"
	.string "Gewicht von POKéMON-Artikeln.$"

Text_Blueprint:
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"
