gText_Oak_Welcome::
	.string "Hi! Entschuldige die Verspätung!\p"
	.string "Willkommen in der Welt der POKéMON!\p"
	.string "Mein Name ist EICH.\p"
	.string "Man nennt mich den POKéMON-\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Oak_Pokemon::
	.string "Das ist ein sogenanntes “POKéMON”.\p"
	.string "\n"
	.string "$"

gText_Oak_MainSpeech::
	.string "Diese Welt wird von Wesen bewohnt,\n"
	.string "die man POKéMON nennt.\p"
	.string "Menschen und POKéMON leben zusammen\n"
	.string "und helfen einander.\p"
	.string "Für manche Leute sind POKéMON Haustiere,\n"
	.string "andere tragen Kämpfe mit ihnen aus.\p"
	.string "Leider wissen wir noch nicht alles\n"
	.string "über POKéMON.\p"
	.string "Es gibt noch viele Geheimnisse zu lüften.\n"
	.string "Darum studiere ich POKéMON\n"
	.string "tagaus, tagein!\p"
	.string "$"

gText_Oak_AndYouAre::
	.string "Und wer bist du?$"

gText_Oak_BoyOrGirl::
	.string "Bist du ein Junge?\n"
	.string "Oder ein Mädchen?$"

gText_Oak_WhatChallenge::
	.string "Welche Art Herausforderung\n"
	.string "erwartest du?$"

gText_Oak_ChallengeSelected::
	.string "Das klingt für mich nach\n"
	.string "genau dem richtigen Niveau!$"

gText_Oak_ChallengeDisclaimer::
	.string "Welche Art Herausforderung\n"
	.string "erwartest du?\p"
	.string "{COLOR RED}Die folgenden Einstellungen können später\n"
	.string " am PC geändert werden.\l"
	.string "Du kannst die Einstellungen zu Nuzlocke\l"
	.string "Randomisierer, Schwierigkeit und\l"
	.string "Herausforderungen nur einfacher\l"
	.string "stellen, nicht schwerer.$"

gText_Oak_WhatsYourName::
	.string "Wie lautet dein Name?$"

gText_Oak_SoItsPlayer::
	.string "Ah! Du bist also {PLAYER}{KUN}?$"

gText_Oak_YourePlayer::
	.string "{PLAYER}{KUN}, bist du bereit?\p"
	.string "Dein eigenes POKéMON-Abenteuer\n"
	.string "erwartet dich.\p"
	.string "$"

gText_Oak_AreYouReady::
	.string "Dich erwarten tolle Dinge,\n"
	.string "aber auch harte Zeiten.\p"
	.string "Eine Welt voller Träume und\n"
	.string "aufregender POKéMON-Abenteuer\n"
	.string "erwartet dich! Mach dich bereit!\p"
	.string "Ich treffe dich später!\p"
	.string "$"
