	.align 2
gText_ConfirmSave::
	.string "Möchtest du das Spiel speichern?$"

gText_AlreadySavedFile::
	.string "Es gibt bereits einen Spielstand.\n"
	.string "Spielstand überschreiben?$"

gText_SavingDontTurnOff::
	.string "SPEICHERN… BITTE DAS GERÄT\n"
	.string "NICHT AUSSCHALTEN.$"

gText_PlayerSavedGame::
	.string "{PLAYER} hat das Spiel gespeichert.$"

gText_DifferentSaveFile::
	.string "ACHTUNG!\p"
	.string "Es gibt bereits einen Spielstand.\p"
	.string "Wenn jetzt gesichert wird, geht\n"
	.string "der andere Spielstand mit allen\l"
	.string "Items und POKéMON für immer\l"
	.string "verloren.\p"
	.string "Bist du sicher, dass du sichern\n"
	.string "und den anderen Spielstand\l"
	.string "überschreiben möchtest?$"

gText_SaveError::
	.string "Save error.\p"
	.string "Please exchange the\n"
	.string "backup memory.$"

gText_SavingDontTurnOffPower::
	.string "SPEICHERN… BITTE DAS GERÄT\n"
	.string "NICHT AUSSCHALTEN.$"
